// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUGxZbB1zxRSYpjdp-C0Z70z-ZSb_He1M',
    appId: '1:679687286116:web:35afce992c71bc40f49e71',
    messagingSenderId: '679687286116',
    projectId: 'dextraworkspace',
    authDomain: 'dextraworkspace.firebaseapp.com',
    storageBucket: 'dextraworkspace.firebasestorage.app',
    measurementId: 'G-V2BJ6YLLX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmJvqI5xw2Qq3fym67XTEFZuoetiOYuF0',
    appId: '1:679687286116:android:3d46add848eea658f49e71',
    messagingSenderId: '679687286116',
    projectId: 'dextraworkspace',
    storageBucket: 'dextraworkspace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvW4eWdZILipHmH15D3WxihrKp4qux4vo',
    appId: '1:679687286116:ios:af74f5f2ee8c7a45f49e71',
    messagingSenderId: '679687286116',
    projectId: 'dextraworkspace',
    storageBucket: 'dextraworkspace.firebasestorage.app',
    iosBundleId: 'com.example.serverMaintance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvW4eWdZILipHmH15D3WxihrKp4qux4vo',
    appId: '1:679687286116:ios:af74f5f2ee8c7a45f49e71',
    messagingSenderId: '679687286116',
    projectId: 'dextraworkspace',
    storageBucket: 'dextraworkspace.firebasestorage.app',
    iosBundleId: 'com.example.serverMaintance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUGxZbB1zxRSYpjdp-C0Z70z-ZSb_He1M',
    appId: '1:679687286116:web:de37b73842645ca1f49e71',
    messagingSenderId: '679687286116',
    projectId: 'dextraworkspace',
    authDomain: 'dextraworkspace.firebaseapp.com',
    storageBucket: 'dextraworkspace.firebasestorage.app',
    measurementId: 'G-DSBTHM01TY',
  );
}
